'use client';
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import {annualHighlights,heroMessages,monthlyHighlights} from './intelligence-data';
import {publicAsset,siteHref} from './site-paths';

type Story={id:string;sector:string;relevance:string;event:string;title:string;summary:string;score:number;publishedDate:string;eventDate?:string;dateNote?:string;source:string;url:string;tags:string[]};
type Resource={id:string;type:string;title:string;publisher:string;date:string;sector:string;tags:string[];summary:string;insight:string;url:string;featured:boolean};
type SummaryBlock={label:string;title:string;range:string;copy:string;words:[string,number][]};
type AutoPayload={updatedAt?:string;weekRange?:string;monthLabel?:string;stories?:Story[];sectorInsights?:[string,string,string,string][];summary?:{week:SummaryBlock;month:SummaryBlock};monthlyHighlights?:typeof monthlyHighlights;annualHighlights?:typeof annualHighlights};
type ImportRow=Record<string,unknown>;
const isRecord=(value:unknown):value is ImportRow=>typeof value==='object'&&value!==null;
const stringValue=(value:unknown,fallback='')=>typeof value==='string'?value:fallback;
const stringList=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];
const initialStories:Story[]=[
{id:'cn-carbon-allocation-2026',sector:'高排放行业',relevance:'直接 ESG',event:'政策',title:'生态环境部原则通过发电、钢铁、水泥和铝冶炼行业碳配额方案',summary:'8月24日，生态环境部常务会议原则通过全国碳市场相关年度配额总量和分配方案，并提出稳妥推行免费与有偿相结合、实施配额总量控制，强化碳排放数据质量全过程监管。',score:10,publishedDate:'2026.08.24',eventDate:'2026.08.24',source:'中国生态环境部',url:'https://www.mee.gov.cn/ywdt/hjywnews/202608/t20260824_1164432.shtml',tags:['全国碳市场','钢铁','水泥','铝']},
{id:'es-data-centres-2026',sector:'人工智能',relevance:'直接 ESG',event:'征求意见',title:'西班牙拟对数据中心设置能源、水资源与数字主权硬约束',summary:'西班牙政府8月27日启动紧急公众咨询，拟要求数据中心达到严格能效和水效标准，并由新增可再生能源逐小时覆盖至少80%的用能；运营主体及相关运营数据还须受欧盟法律约束。',score:9,publishedDate:'2026.08.27',eventDate:'2026.08.27',source:'西班牙数字化转型部',url:'https://digital.gob.es/comunicacion/notas-prensa/mtdfp/2026/08/el-gobierno-plantea-impulsar-los-centros-de-datos-sostenibles--e',tags:['数据中心','可再生能源','水效']},
{id:'au-climate-disclosure-2026',sector:'企业出海',relevance:'直接 ESG',event:'披露',title:'澳大利亚明确联邦机构气候披露与排放清单的数字化发布要求',summary:'澳大利亚财政部8月29日发布指引：自2025—26报告期起，联邦实体和公司需要通过透明度门户的数字年度报告工具发布气候披露与排放清单。',score:8,publishedDate:'2026.08.29',source:'澳大利亚财政部',url:'https://www.finance.gov.au/government/managing-commonwealth-resources/commonwealth-climate-disclosure-rmg-140/publishing-climate-disclosure',tags:['气候披露','排放清单','数字报告']},
{id:'uk-plug-solar-2026',sector:'新能源',relevance:'直接 ESG',event:'政策生效',title:'英国正式允许家用即插即用太阳能板进入市场',summary:'英国政府8月26日发布公告，法律变化自8月27日起生效，即插即用太阳能板可合法购买和使用；合规设备最高800瓦，预计可覆盖普通家庭最高20%的用电。',score:8,publishedDate:'2026.08.26',eventDate:'2026.08.27',dateNote:'生效',source:'英国能源安全与净零部',url:'https://www.gov.uk/government/news/households-can-save-as-plug-in-solar-panels-come-to-market',tags:['分布式光伏','能源可负担性','安全标准']},
{id:'cn-envtech-finance-2026',sector:'绿色金融',relevance:'直接 ESG',event:'政策',title:'中国五部门推动生态环境科技创新形成多元化投入机制',summary:'生态环境部等五部门于8月20日成文并公开指导意见，提出形成覆盖基础研究到产业应用、政府到金融机构的投入模式，并要求到2030年丰富政策工具和金融产品体系。',score:8,publishedDate:'2026.08.27',eventDate:'2026.08.20',dateNote:'成文',source:'中国生态环境部',url:'https://www.mee.gov.cn/xxgk2018/xxgk/xxgk03/202608/t20260827_1164595.html',tags:['科技金融','绿色金融','成果转化']},
{id:'cn-hcfc22-2026',sector:'高排放行业',relevance:'直接 ESG',event:'监管',title:'中国推进淘汰以 HCFC-22 为制冷剂的多联式空调产品',summary:'生态环境部8月24日原则通过相关公告，强调按时间节点推进HCFC-22淘汰、加强监督执法，并促进绿色替代技术研发与应用。',score:7,publishedDate:'2026.08.24',eventDate:'2026.08.24',source:'中国生态环境部',url:'https://www.mee.gov.cn/ywdt/hjywnews/202608/t20260824_1164432.shtml',tags:['制冷剂','蒙特利尔议定书','绿色替代']},
{id:'nsw-data-centres-2026',sector:'人工智能',relevance:'间接 ESG',event:'政策咨询',title:'新南威尔士州就数据中心电网接入与成本分摊改革征求意见',summary:'咨询期于8月17日启动，8月24日举行公开说明会。改革目标包括改善数据中心接网规划、避免将新增电力成本转嫁给居民和小企业，并支持新增可再生能源与储能。',score:7,publishedDate:'2026.08.17',eventDate:'2026.08.24',dateNote:'说明会',source:'新南威尔士州政府',url:'https://www.nsw.gov.au/have-your-say/nsw-data-centre-reforms',tags:['数据中心','电网接入','成本分摊']},
{id:'uk-clean-power-pilot-2026',sector:'新能源',relevance:'间接 ESG',event:'示范项目',title:'英国西部启动面向大型活动和影视制作的清洁电力试点',summary:'西英格兰联合管理局8月28日公布试点，通过可移动清洁电源替代活动现场的化石燃料发电，探索现场娱乐和影视制作的低碳供能模式。',score:6,publishedDate:'2026.08.28',eventDate:'2026.08.28',source:'西英格兰联合管理局',url:'https://www.westofengland-ca.gov.uk/news/climate-bristol-pilot-creates-national-clean-power-leap/',tags:['清洁电力','文化产业','示范项目']},
{id:'oecd-just-transition-sentiment-2026',sector:'高排放行业',relevance:'直接 ESG',event:'研究发布',title:'OECD：气候行动需要同步回应公正转型与经济安全',summary:'OECD于8月31日发布工作论文，综合27个成员国数据发现，超过三分之二受访者表达气候关切，但对进一步政策行动的支持度低于关切度；经济脆弱家庭与排放密集行业劳动者更担忧转型成本。论文建议通过透明沟通、补偿措施和包容性设计提高政策可接受度。',score:8,publishedDate:'2026.08.31',eventDate:'2026.08.31',dateNote:'研究发布',source:'OECD',url:'https://www.oecd.org/en/publications/taking-the-temperature-on-climate-change-and-on-just-transition-policies_96cf0561-en.html',tags:['公正转型','气候政策','转型成本','工作论文']},
];
const sectorInsights=[['人工智能','西班牙与新南威尔士州的政策都把数据中心增长与电网成本、新增清洁电力及水资源效率绑定，算力扩张正进入资源约束型监管阶段。','2 个信号','↑'],['新能源','英国将即插即用光伏合法化，同时推动可移动清洁电源试点，分布式与场景化应用成为本周新增量。','2 个信号','↑'],['企业出海','澳大利亚公共部门气候信息开始通过统一数字工具发布；跨境企业需要关注机器可读披露和排放数据口径的扩散。','1 个信号','→'],['高排放行业','中国碳市场配额方案继续强化配额与数据质量约束；OECD 的跨国证据则提醒企业，减排方案还需要同步处理劳动者经济安全、成本分配与补偿机制。','3 个信号','↑'],['绿色金融','中国五部门把财政、金融与社会资本纳入生态环境科技创新投入体系，政策目标从项目补贴扩展到全周期融资。','1 个信号','↑']];
const summaryData={
 week:{label:'本周总结',title:'硬约束之外，公正转型正在成为执行条件',range:'2026.08.24—08.31',copy:'本周最强信号仍来自碳市场配额、数据中心电力与水资源约束，以及披露数据的数字化要求。OECD 最新跨国证据进一步表明，高排放行业若忽视经济安全、成本分配与补偿机制，气候政策的社会接受度可能成为落地瓶颈。',words:[['政策',10],['能源',9],['数据中心',8],['碳市场',8],['气候政策',8],['公正转型',7],['披露',7],['可再生能源',7],['监管',6],['高排放行业',6],['转型成本',6],['电网接入',5],['水资源',5],['绿色金融',5],['排放数据',5],['经济安全',4],['补偿机制',4],['钢铁',4],['水泥',4],['数字主权',3]]},
 month:{label:'本月总结',title:'披露、算力、跨境碳成本与转型公平正在形成同一条约束链',range:'2026.08.01—08.31',copy:'8月的重点变化共同指向一件事：企业的能源来源、排放数据和供应链证据正被制度化连接，而转型成本如何分配也开始影响政策可接受度。数据中心、高排放制造和出海企业需要同时评估资源许可、可验证披露、劳动者影响与跨境合规成本。',words:[['气候披露',10],['数据中心',10],['可再生能源',9],['碳边境',9],['供应链',8],['市场准入',8],['碳成本',8],['公正转型',7],['人工智能',7],['电力系统',7],['水效',6],['排放核算',6],['绿色金融',6],['高排放行业',6],['转型成本',5],['尽职调查',5],['储能',5],['经济安全',4],['数字报告',4],['补偿机制',4]]}
} as const;

export default function Home(){
 const [stories,setStories]=useState(initialStories);const [query,setQuery]=useState('');const [sector,setSector]=useState('全部行业');const [view,setView]=useState<'all'|'favorites'|'removed'>('all');const [favorites,setFavorites]=useState<string[]>([]);const [removed,setRemoved]=useState<string[]>([]);const [notice,setNotice]=useState('');
 const [resources,setResources]=useState<Resource[]>([]);const [resourceQuery,setResourceQuery]=useState('');const [resourceType,setResourceType]=useState('全部类型');const [selectedResource,setSelectedResource]=useState<Resource|null>(null);const [libraryUpdated,setLibraryUpdated]=useState('');const [resourceLimit,setResourceLimit]=useState(12);
 const [heroMessage,setHeroMessage]=useState<(typeof heroMessages)[number]>(heroMessages[0]);const [periodScope,setPeriodScope]=useState<'month'|'year'>('month');const [summaryScope,setSummaryScope]=useState<'week'|'month'>('week');
 const [autoPayload,setAutoPayload]=useState<AutoPayload|null>(null);
 const [importOpen,setImportOpen]=useState(false);const [importToLibrary,setImportToLibrary]=useState(true);const [importFile,setImportFile]=useState<File|null>(null);
 const [webSearchOpen,setWebSearchOpen]=useState(false);const [webSearchContext,setWebSearchContext]=useState<'stories'|'library'>('stories');const [webQuery,setWebQuery]=useState('');const [webSearchType,setWebSearchType]=useState<'official'|'academic'|'all'>('official');
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setFavorites(JSON.parse(localStorage.getItem('esg-favorites')||'[]'));setRemoved(JSON.parse(localStorage.getItem('esg-removed')||'[]'))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>setHeroMessage(heroMessages[Math.floor(Math.random()*heroMessages.length)]),0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{fetch(publicAsset('auto-intelligence.json')).then(r=>r.ok?r.json():null).then((data:unknown)=>{if(!isRecord(data))return;const payload=data as AutoPayload;setAutoPayload(payload);if(Array.isArray(payload.stories)&&payload.stories.length)setStories(payload.stories)}).catch(()=>{})},[]);
 useEffect(()=>{let userRows:Resource[]=[];try{userRows=JSON.parse(localStorage.getItem('synerplat-user-library')||'[]')}catch{}fetch(publicAsset('research-library.json')).then(r=>r.json()).then((data:unknown)=>{const payload=isRecord(data)?data:{};const official=Array.isArray(payload.items)?payload.items as Resource[]:[];setResources([...userRows,...official.filter(x=>!userRows.some(u=>u.url===x.url))]);setLibraryUpdated(stringValue(payload.updatedAt))}).catch(()=>{setResources(userRows);setNotice('官方资料库暂时无法加载，已显示本机导入资料')})},[]);
 const update=(key:string,value:string[])=>{localStorage.setItem(key,JSON.stringify(value));if(key==='esg-favorites')setFavorites(value);else setRemoved(value)};
 const filtered=useMemo(()=>stories.filter(s=>{const match=!query||(s.title+s.summary+s.tags.join('')).toLowerCase().includes(query.toLowerCase());const sectorMatch=sector==='全部行业'||s.sector===sector;const stateMatch=view==='favorites'?favorites.includes(s.id)&&!removed.includes(s.id):view==='removed'?removed.includes(s.id):!removed.includes(s.id);return match&&sectorMatch&&stateMatch}),[stories,query,sector,view,favorites,removed]);
 const pickImport=(event:ChangeEvent<HTMLInputElement>)=>setImportFile(event.target.files?.[0]||null);
 const classifyResource=(row:ImportRow)=>{const text=`${stringValue(row.type)} ${stringValue(row.title)} ${stringValue(row.publisher)||stringValue(row.source)} ${stringValue(row.url)}`.toLowerCase();if(/journal|doi|nature|science|arxiv|论文|学术/.test(text))return '学术论文';if(/working paper|工作论文|preprint/.test(text))return '工作论文';if(/law|regulation|directive|policy|政府|部委|政策|法规/.test(text))return '政策法规';return '行业报告'};
 const processImport=()=>{if(!importFile){setNotice('请先选择 JSON 文件');return}const reader=new FileReader();reader.onload=()=>{try{const parsed:unknown=JSON.parse(String(reader.result));const rawRows=Array.isArray(parsed)?parsed:isRecord(parsed)&&Array.isArray(parsed.items)?parsed.items:[];const rows=rawRows.filter(isRecord);if(!rows.length)throw new Error();if(importToLibrary){const imported:Resource[]=rows.map((x,i)=>({id:stringValue(x.id,`user-${Date.now()}-${i}`),type:classifyResource(x),title:stringValue(x.title,'未命名资料'),publisher:stringValue(x.publisher)||stringValue(x.source,'用户导入'),date:stringValue(x.published_date)||stringValue(x.date,'日期待核'),sector:stringList(x.sectors)[0]||stringValue(x.sector,'其他'),tags:Array.from(new Set(['用户导入',...stringList(x.tags),...stringList(x.esg_tags),...stringList(x.event_tags)])),summary:stringValue(x.summary)||stringValue(x.abstract,'暂无摘要'),insight:stringValue(x.insight,'用户导入资料，使用前请核验作者、发布日期与原始来源。'),url:stringValue(x.url,'#'),featured:false}));const existingUser:Resource[]=(()=>{try{return JSON.parse(localStorage.getItem('synerplat-user-library')||'[]')}catch{return []}})();const merged=[...imported,...existingUser.filter(x=>!imported.some(n=>n.url!=='#'&&n.url===x.url))];localStorage.setItem('synerplat-user-library',JSON.stringify(merged));setResources(current=>[...imported,...current.filter(x=>!imported.some(n=>n.url!=='#'&&n.url===x.url))]);setNotice(`已归类并加入资料库 ${imported.length} 条，标注为“用户导入”`)}else{const importedStories:Story[]=rows.map((x,i)=>({id:stringValue(x.id,`import-${Date.now()}-${i}`),sector:stringList(x.sectors)[0]||stringValue(x.sector,'其他'),relevance:stringValue(x.relevance,'待分类'),event:stringList(x.event_tags)[0]||stringValue(x.event,'新闻'),title:stringValue(x.title,'未命名动态'),summary:stringValue(x.summary),score:Number(x.materiality_score||x.score||0),publishedDate:stringValue(x.published_date)||stringValue(x.date,'日期待核'),eventDate:x.event_date?String(x.event_date):undefined,source:stringValue(x.source,'导入数据'),url:stringValue(x.url,'#'),tags:[...stringList(x.esg_tags),...stringList(x.event_tags)]}));setStories(importedStories);setNotice(`已导入 ${importedStories.length} 条动态，未写入资料库`)}setImportOpen(false);setImportFile(null)}catch{setNotice('导入失败：请使用包含 items 数组的 JSON 文件，并至少提供标题、摘要、日期和来源链接')}};reader.readAsText(importFile)};
 const openWebSearch=(context:'stories'|'library')=>{setWebSearchContext(context);setWebSearchType(context==='library'?'academic':'official');setWebQuery(context==='stories'?'ESG 重大政策 人工智能 新能源 出海 高排放':'ESG 气候披露 能源转型 学术研究 政策报告');setWebSearchOpen(true)};
 const runWebSearch=()=>{const trusted='(site:gov.cn OR site:mee.gov.cn OR site:europa.eu OR site:gov.uk OR site:oecd.org OR site:iea.org OR site:unep.org OR site:ipcc.ch)';const q=webSearchType==='official'?`${webQuery} ${trusted}`:webSearchType==='academic'?webQuery:`${webQuery} ESG policy research`;const url=webSearchType==='academic'?`https://scholar.google.com/scholar?q=${encodeURIComponent(q)}`:`https://www.google.com/search?q=${encodeURIComponent(q)}`;window.open(url,'_blank','noopener,noreferrer');setWebSearchOpen(false)};
 const exportData=()=>{const blob=new Blob([JSON.stringify({items:filtered},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='esg-signal-selection.json';a.click();URL.revokeObjectURL(a.href)};
 const visibleResources=useMemo(()=>resources.filter(r=>(resourceType==='全部类型'||r.type===resourceType)&&(!resourceQuery||(r.title+r.publisher+r.summary+r.tags.join('')).toLowerCase().includes(resourceQuery.toLowerCase()))),[resources,resourceQuery,resourceType]);
 const activeSummary=autoPayload?.summary||summaryData;const activeSectors=autoPayload?.sectorInsights?.length?autoPayload.sectorInsights:sectorInsights;
 const activeMonthly=[...(autoPayload?.monthlyHighlights||[]),...monthlyHighlights].filter((item,index,all)=>all.findIndex(other=>other.url===item.url)===index);
 const activeAnnual=[...(autoPayload?.annualHighlights||[]),...annualHighlights].filter((item,index,all)=>all.findIndex(other=>other.url===item.url)===index);
 const weekRange=autoPayload?.weekRange||'2026.08.24—08.31';const monthLabel=autoPayload?.monthLabel||'2026年8月';
 const sectorCount=new Set(stories.map(item=>item.sector)).size;const directRate=stories.length?Math.round(stories.filter(item=>item.relevance==='直接 ESG').length/stories.length*100):0;const policyCount=stories.filter(item=>/政策|监管|披露|征求意见/.test(item.event)).length;
 return <main><header className="topbar"><a className="brand designed" href="#"><span>Syner</span>Plat</a><nav><a href="#overview">本周洞察</a><a href="#periods">月度/年度</a><a href="#stories">新闻库</a><a href="#library">研究资料</a><a href={siteHref('data/')}>数据洞察</a></nav><button className="outline import-trigger" onClick={()=>setImportOpen(true)}>导入</button></header>
 <section className="hero refined" id="overview"><div className="hero-copy"><p className="eyebrow">WEEKLY INTELLIGENCE · {weekRange}</p><h1>{heroMessage[0]}</h1><p className="lede">{heroMessage[1]}</p><div className="hero-actions"><a className="primary" href="#stories">查看本周重大动态</a><a className="text-link" href={siteHref('data/')}>进入数据洞察 →</a><span>真实来源 · 每日更新</span></div></div><aside className="signal-card"><p>本周核心信号</p><strong>资源与排放约束<br/>正在进入企业的<br/><em>市场准入条件</em></strong><div className="signal-meta"><span>{stories.length} 条已核验动态</span><span>↑ {sectorCount} 个行业</span></div></aside><div className="hero-grid-mark" aria-hidden="true"/></section>
 <section className="stats"><a href={siteHref('data/')}><b>{stories.length.toString().padStart(2,'0')}</b><span>重大动态</span><small>查看数据 →</small></a><a href={siteHref('data/')}><b>{policyCount.toString().padStart(2,'0')}</b><span>政策与监管动态</span><small>查看数据 →</small></a><a href={siteHref('data/')}><b>{sectorCount.toString().padStart(2,'0')}</b><span>覆盖行业</span><small>查看数据 →</small></a><a href={siteHref('data/')}><b>{directRate}%</b><span>直接 ESG</span><small>查看数据 →</small></a></section>
 <section className="periods" id="periods"><div className="section-head"><div><p className="eyebrow">PRIORITY WINDOWS</p><h2>从本周，看到更长的时间尺度</h2></div><div className="scope-toggle"><button className={periodScope==='month'?'active':''} onClick={()=>setPeriodScope('month')}>本月重点</button><button className={periodScope==='year'?'active':''} onClick={()=>setPeriodScope('year')}>本年度重点</button></div></div><div className="period-intro"><b>{periodScope==='month'?monthLabel:'2026年度'}</b><p>{periodScope==='month'?'筛选影响市场准入、资源约束、资本开支与披露义务的月度关键变化。':'年度视图只保留制度级与跨行业事件，不追求普通新闻的完整收录。'}</p><a href={siteHref('data/#timeline')}>进入完整时间轴 →</a></div><div className="period-cards">{[...(periodScope==='month'?activeMonthly:activeAnnual)].sort((a,b)=>b.score-a.score||b.date.localeCompare(a.date)).slice(0,6).map(h=><article key={h.title}><div><span>{h.date}</span><b>{h.score}/10</b></div><small>{h.sector} · {h.source}</small><h3>{h.title}</h3><p>{h.summary}</p><a href={h.url} target="_blank" rel="noopener noreferrer">原始来源 ↗</a></article>)}</div></section>
 <section className="summary-hub" id="summary"><div className="summary-head"><div><p className="eyebrow">EXECUTIVE SUMMARY</p><h2>{activeSummary[summaryScope].label}</h2></div><div className="scope-toggle summary-toggle"><button className={summaryScope==='week'?'active':''} onClick={()=>setSummaryScope('week')}>本周总结</button><button className={summaryScope==='month'?'active':''} onClick={()=>setSummaryScope('month')}>本月总结</button></div></div><div className="summary-lead"><span>{activeSummary[summaryScope].range}</span><h3>{activeSummary[summaryScope].title}</h3><p>{activeSummary[summaryScope].copy}</p></div><div className="signal-visuals"><div className="word-cloud" aria-label={`${activeSummary[summaryScope].label}关键词词云`}>{activeSummary[summaryScope].words.map(([word,count],i)=><span key={word} className={`cloud-word level-${count>=8?'high':count>=5?'medium':'low'} word-${i%7}`} style={{fontSize:`${16+count*3.2}px`}}>{word}</span>)}</div><div className="frequency-panel"><div><p>高频词</p>{activeSummary[summaryScope].words.filter(([,count])=>count>=7).map(([word,count])=><div className="frequency-row" key={word}><span>{word}</span><i><b style={{width:`${count*10}%`}}/></i><strong>{count}</strong></div>)}</div><div><p>中频词</p>{activeSummary[summaryScope].words.filter(([,count])=>count>=4&&count<7).map(([word,count])=><div className="frequency-row" key={word}><span>{word}</span><i><b style={{width:`${count*10}%`}}/></i><strong>{count}</strong></div>)}</div><small>频率为本期去重标题与摘要的归一化提及指数，不代表全文词频。</small><a className="data-inline-link" href={siteHref('data/')}>查看更多数据分布 →</a></div></div></section>
 <section className="content" id="stories"><div className="section-head"><div><p className="eyebrow">MATERIAL DEVELOPMENTS</p><h2>本周重大动态</h2><small className="date-disclaimer">日期可能有不准确，请仔细核查。</small></div><p>显示“发布”与“事件/生效”日期；链接直达原始页面</p></div><div className="toolbar"><input aria-label="搜索新闻" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、摘要或关键词…"/><select aria-label="选择行业" value={sector} onChange={e=>setSector(e.target.value)}>{['全部行业',...Array.from(new Set(stories.map(s=>s.sector)))].map(x=><option key={x}>{x}</option>)}</select><div className="view-tabs">{([['all','当前'],['favorites',`收藏 ${favorites.length}`],['removed',`已移除 ${removed.length}`]] as const).map(([k,label])=><button className={view===k?'active':''} onClick={()=>setView(k)} key={k}>{label}</button>)}</div><button className="web-search-button" onClick={()=>openWebSearch('stories')}>联网搜索</button><button className="export" onClick={exportData}>导出结果</button></div>{notice&&<p className="notice" role="status">{notice}</p>}<div className="story-grid">{filtered.map((story,i)=><article className="story" key={story.id}><div className="story-top"><span>{String(i+1).padStart(2,'0')} · 发布 {story.publishedDate}{story.eventDate&&story.eventDate!==story.publishedDate?` · ${story.dateNote||'事件'} ${story.eventDate}`:''}</span><b>{story.score}/10</b></div><div className="chips"><span>{story.sector}</span><span>{story.relevance}</span><span>{story.event}</span></div><h3>{story.title}</h3><p>{story.summary}</p><div className="story-actions"><a href={story.url} target="_blank" rel="noopener noreferrer">{story.source} <span>↗</span></a><button aria-label="收藏" className={favorites.includes(story.id)?'saved':''} onClick={()=>update('esg-favorites',favorites.includes(story.id)?favorites.filter(x=>x!==story.id):[...favorites,story.id])}>★</button><button aria-label={removed.includes(story.id)?'恢复':'移除'} onClick={()=>update('esg-removed',removed.includes(story.id)?removed.filter(x=>x!==story.id):[...removed,story.id])}>{removed.includes(story.id)?'↩':'×'}</button></div></article>)}{!filtered.length&&<div className="empty">没有符合当前筛选的新闻。</div>}</div></section>
 <section className="sectors" id="sectors"><div className="section-head"><div><p className="eyebrow">SECTOR LENS</p><h2>行业细分观察</h2></div><p>方向、催化因素与下一步观察点</p></div><div className="sector-list">{activeSectors.map(([name,text,count,arrow],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{text}</p><b>{count}　{arrow}</b></article>)}</div></section>
 <section className="library" id="library"><div className="section-head"><div><p className="eyebrow">RESEARCH LIBRARY</p><h2>研究资料库</h2></div><p>{libraryUpdated?`最后更新：${new Date(libraryUpdated).toLocaleString('zh-CN')}`:'正在加载资料…'} · 每日更新</p></div><div className="library-dashboard"><div><b>{resources.length}</b><span>可靠资料</span></div>{['政策法规','行业报告','学术论文','工作论文'].map(type=><div key={type}><b>{resources.filter(r=>r.type===type).length}</b><span>{type}</span></div>)}</div><div className="library-tools"><input value={resourceQuery} onChange={e=>setResourceQuery(e.target.value)} placeholder="检索标题、机构、摘要或关键词…"/><select value={resourceType} onChange={e=>setResourceType(e.target.value)}>{['全部类型',...Array.from(new Set(resources.map(r=>r.type)))].map(x=><option key={x}>{x}</option>)}</select><button className="web-search-button" onClick={()=>openWebSearch('library')}>联网搜索</button></div><div className="resource-list">{visibleResources.slice(0,resourceQuery?50:resourceLimit).map(resource=><article key={resource.id} className={resource.featured?'featured':''}><div className="resource-index"><span>{resource.type}</span><small>{resource.date}</small></div><div><div className="resource-tags">{resource.tags.map(tag=><span key={tag}>{tag}</span>)}</div><h3>{resource.title}</h3><p>{resource.summary}</p><small>{resource.publisher}</small></div><button onClick={()=>setSelectedResource(resource)}>查看资料 <span>↗</span></button></article>)}{!visibleResources.length&&<div className="empty">没有匹配的资料。</div>}</div>{!resourceQuery&&resourceLimit<visibleResources.length&&<button className="load-more" onClick={()=>setResourceLimit(x=>x+12)}>加载更多资料 · {visibleResources.length-resourceLimit} 条待查看</button>}</section>
 {importOpen&&<div className="modal-overlay" role="dialog" aria-modal="true" aria-label="导入资料" onClick={()=>setImportOpen(false)}><article className="action-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setImportOpen(false)} aria-label="关闭">×</button><p className="eyebrow">IMPORT</p><h2>导入</h2><label className="file-drop"><span>{importFile?importFile.name:'选择 JSON 文件'}</span><small>支持周报数据或包含 items 数组的资料清单</small><input type="file" accept="application/json,.json" onChange={pickImport}/></label><fieldset><legend>是否作为资料更新到库中？</legend><label><input type="radio" name="library-import" checked={importToLibrary} onChange={()=>setImportToLibrary(true)}/> 是，归类后加入资料库</label><label><input type="radio" name="library-import" checked={!importToLibrary} onChange={()=>setImportToLibrary(false)}/> 否，仅替换当前动态视图</label></fieldset><div className="import-guidance"><b>适合加入资料库的文件</b><ul><li>政府或监管政策、国际组织报告、行业白皮书、同行评审论文或明确标注的工作论文；</li><li>每条至少包含标题、摘要、作者/发布机构、日期与可访问的原始链接；</li><li>不建议导入无出处截图、宣传稿、重复转载或缺少作者与日期的材料。</li></ul><small>选择“是”后会自动初步分类，并加上“用户导入”标签。当前版本保存在本机浏览器中，请在正式研究引用前再次核验。</small></div><button className="primary modal-primary" onClick={processImport}>确认导入</button></article></div>}
 {webSearchOpen&&<div className="modal-overlay" role="dialog" aria-modal="true" aria-label="联网搜索" onClick={()=>setWebSearchOpen(false)}><article className="action-modal search-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setWebSearchOpen(false)} aria-label="关闭">×</button><p className="eyebrow">LIVE SEARCH</p><h2>{webSearchContext==='stories'?'检索重大动态':'检索研究资料'}</h2><p>搜索将在新标签页打开。政策与新闻模式优先限定政府、监管机构和国际组织；学术模式使用 Google Scholar。</p><label className="search-field"><span>关键词</span><input autoFocus value={webQuery} onChange={e=>setWebQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')runWebSearch()}}/></label><div className="search-type"><button className={webSearchType==='official'?'active':''} onClick={()=>setWebSearchType('official')}>权威政策 / 新闻</button><button className={webSearchType==='academic'?'active':''} onClick={()=>setWebSearchType('academic')}>学术文献</button><button className={webSearchType==='all'?'active':''} onClick={()=>setWebSearchType('all')}>综合搜索</button></div><div className="search-note">联网结果不会自动写入资料库。建议打开原始来源核验日期、作者和版本，再通过“导入”加入。</div><button className="primary modal-primary" onClick={runWebSearch}>开始联网搜索 ↗</button></article></div>}
 {selectedResource&&<div className="resource-overlay" role="dialog" aria-modal="true" aria-label={selectedResource.title} onClick={()=>setSelectedResource(null)}><article className="resource-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelectedResource(null)} aria-label="关闭">×</button><p className="eyebrow">{selectedResource.type} · {selectedResource.date}</p><h2>{selectedResource.title}</h2><p className="drawer-publisher">{selectedResource.publisher}</p><div className="resource-tags">{selectedResource.tags.map(tag=><span key={tag}>{tag}</span>)}</div><h4>内容摘要</h4><p>{selectedResource.summary}</p><h4>研究价值</h4><p>{selectedResource.insight}</p><div className="source-note">来源已核验为官方机构、同行评审期刊或明确标注的工作论文。访问权限取决于原发布方。</div><a className="primary" href={selectedResource.url} target="_blank" rel="noopener noreferrer">打开原文 / PDF ↗</a></article></div>}
 <section className="method" id="methodology"><div><p className="eyebrow">METHODOLOGY</p><h2>不是新闻聚合，<br/>而是重大性筛选。</h2></div><div><p>每条信息按 ESG 相关性、影响范围、实际后果、信源权威性和新颖性评分。通常仅保留 6/10 以上内容，并区分事件日期与发布日期。</p><p>资料库优先收录政府、监管机构、国际组织、同行评审期刊与明确标注的工作论文。预印本与机构研究会保留来源属性，避免与已同行评审成果混淆。</p></div></section><footer><a className="brand designed" href="#"><span>Syner</span>Plat</a><p>每天更新，把变化整理成信号。</p><a href="#overview">返回顶部 ↑</a></footer></main>
}
